#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=11

apply_defaults() {
	# first set default, then all interfaces to avoid races with appearing interfaces
	if [ -d /proc/sys/net/ipv6/conf ]; then
		echo 0 > /proc/sys/net/ipv6/conf/default/accept_ra
		for iface in /proc/sys/net/ipv6/conf/*/accept_ra; do
			echo 0 > "$iface"
		done
	fi
}

start() {
	apply_defaults
	for CONF in /etc/sysctl.d/*.conf /etc/sysctl.conf; do
		[ -f "$CONF" ] && sysctl -e -p "$CONF" >&-
	done
}
